export interface Challenge {
  id: number
  title: string
  description: string
  difficulty: 'fácil' | 'medio' | 'difícil'
  type: 'write' | 'complete' | 'fix'
  hint: string
  starterCode: string
  validationQuery: string // query to run to check answer
  expectedCheck: (userResult: any[][], expectedResult: any[][]) => boolean
  category: string
}

function arraysMatch(a: any[][], b: any[][]): boolean {
  if (a.length !== b.length) return false
  const sortA = a.map(r => JSON.stringify(r)).sort()
  const sortB = b.map(r => JSON.stringify(r)).sort()
  return sortA.every((v, i) => v === sortB[i])
}

function countMatch(a: any[][], b: any[][]): boolean {
  return a.length === b.length && a[0]?.[0] === b[0]?.[0]
}

export const CHALLENGES: Challenge[] = [
  {
    id: 1,
    title: 'Seleccionar Todos los Empleados',
    description: 'Escribe una consulta que muestre el nombre y email de todos los empleados.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Usa SELECT con las columnas name y email de la tabla Employees.',
    starterCode: '-- Escribe tu consulta aquí\nSELECT ',
    validationQuery: 'SELECT name, email FROM Employees',
    expectedCheck: arraysMatch,
    category: 'SELECT',
  },
  {
    id: 2,
    title: 'Filtrar Empleados Activos',
    description: 'Completa la consulta para mostrar solo los empleados con status "ACTIVE" y salario mayor a 50000.',
    difficulty: 'fácil',
    type: 'complete',
    hint: 'Usa WHERE con dos condiciones unidas por AND.',
    starterCode: "SELECT name, salary, status\nFROM Employees\nWHERE ___",
    validationQuery: "SELECT name, salary, status FROM Employees WHERE status = 'ACTIVE' AND salary > 50000",
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 3,
    title: 'Unir Empleados con Departamentos',
    description: 'Escribe un INNER JOIN para mostrar el nombre del empleado y el nombre de su departamento.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Une Employees con Departments usando department_id.',
    starterCode: '-- Une empleados con departamentos\n',
    validationQuery: 'SELECT e.name, d.department_name FROM Employees e INNER JOIN Departments d ON e.department_id = d.id',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 4,
    title: 'Empleados sin Departamento',
    description: 'Usa un LEFT JOIN para encontrar los empleados que NO tienen departamento asignado.',
    difficulty: 'medio',
    type: 'write',
    hint: 'LEFT JOIN + WHERE ... IS NULL para encontrar los que no tienen match.',
    starterCode: '-- Encuentra empleados sin departamento\n',
    validationQuery: 'SELECT e.name FROM Employees e LEFT JOIN Departments d ON e.department_id = d.id WHERE d.id IS NULL',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 5,
    title: 'Contar Empleados por Departamento',
    description: 'Cuenta cuántos empleados hay en cada departamento. Muestra el nombre del departamento y la cantidad.',
    difficulty: 'medio',
    type: 'write',
    hint: 'Usa GROUP BY con COUNT() y un JOIN a Departments.',
    starterCode: '-- Cuenta empleados por departamento\n',
    validationQuery: 'SELECT d.department_name, COUNT(e.id) as total FROM Departments d LEFT JOIN Employees e ON d.id = e.department_id GROUP BY d.department_name',
    expectedCheck: arraysMatch,
    category: 'GROUP BY',
  },
  {
    id: 6,
    title: 'Arregla la Consulta',
    description: 'Esta consulta tiene errores de sintaxis. Corrígela para que funcione correctamente.',
    difficulty: 'medio',
    type: 'fix',
    hint: 'Revisa el nombre de las columnas y la sintaxis del WHERE.',
    starterCode: "SELEC nombre, email\nFROM Employee\nWERE status = 'ACTIVE';",
    validationQuery: "SELECT name, email FROM Employees WHERE status = 'ACTIVE'",
    expectedCheck: arraysMatch,
    category: 'Debug',
  },
  {
    id: 7,
    title: 'Top 3 Productos más Caros',
    description: 'Muestra los 3 productos con el precio más alto, ordenados de mayor a menor.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Usa ORDER BY ... DESC con LIMIT 3.',
    starterCode: '-- Top 3 productos más caros\n',
    validationQuery: 'SELECT title, price FROM Products ORDER BY price DESC LIMIT 3',
    expectedCheck: arraysMatch,
    category: 'ORDER BY',
  },
  {
    id: 8,
    title: 'Pedidos con Detalles Completos',
    description: 'Escribe una consulta que muestre: nombre del cliente, título del producto, cantidad y total de cada pedido.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Necesitas unir 3 tablas: Orders, Customers y Products.',
    starterCode: '-- Pedidos con detalles completos\n',
    validationQuery: 'SELECT c.name, p.title, o.quantity, o.total FROM Orders o INNER JOIN Customers c ON o.customer_id = c.id INNER JOIN Products p ON o.product_id = p.id',
    expectedCheck: arraysMatch,
    category: 'Multi-JOIN',
  },
  {
    id: 9,
    title: 'Ingresos Totales por Cliente',
    description: 'Calcula el total gastado por cada cliente, pero solo muestra los que han gastado más de 500. Ordena de mayor a menor.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa SUM() con GROUP BY y HAVING para filtrar.',
    starterCode: '-- Ingresos totales por cliente (> 500)\n',
    validationQuery: 'SELECT c.name, SUM(o.total) as total_spent FROM Customers c INNER JOIN Orders o ON c.id = o.customer_id GROUP BY c.name HAVING SUM(o.total) > 500 ORDER BY total_spent DESC',
    expectedCheck: arraysMatch,
    category: 'HAVING',
  },
  {
    id: 10,
    title: 'Subquery: Clientes sin Pedidos',
    description: 'Usando una subconsulta (NOT IN), encuentra los clientes que nunca han realizado un pedido.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa WHERE id NOT IN (SELECT customer_id FROM Orders).',
    starterCode: '-- Clientes que nunca han comprado\n',
    validationQuery: 'SELECT name, email FROM Customers WHERE id NOT IN (SELECT customer_id FROM Orders)',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 11,
    title: 'Columnas con Alias',
    description: 'Muestra el nombre y salario de todos los empleados usando alias: "empleado" para name y "sueldo" para salary.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Usa AS para definir alias de columnas.',
    starterCode: '-- Usa alias para las columnas\nSELECT ',
    validationQuery: 'SELECT name AS empleado, salary AS sueldo FROM Employees',
    expectedCheck: arraysMatch,
    category: 'SELECT',
  },
  {
    id: 12,
    title: 'SELECT con DISTINCT',
    description: 'Obtén la lista de países únicos de la tabla Customers, sin repeticiones.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'DISTINCT elimina los valores duplicados.',
    starterCode: '-- Países únicos\nSELECT ',
    validationQuery: 'SELECT DISTINCT country FROM Customers',
    expectedCheck: arraysMatch,
    category: 'SELECT',
  },
  {
    id: 13,
    title: 'Columna Calculada',
    description: 'Muestra el nombre de cada producto y su precio con un descuento del 15%. Llama a la columna calculada "precio_descuento".',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Multiplica el precio por 0.85 y usa AS.',
    starterCode: '-- Precio con 15% de descuento\nSELECT ',
    validationQuery: 'SELECT title, price * 0.85 AS precio_descuento FROM Products',
    expectedCheck: arraysMatch,
    category: 'SELECT',
  },
  {
    id: 14,
    title: 'Concatenar Columnas',
    description: 'Muestra una sola columna llamada "info" que combine el nombre y email de cada cliente en el formato: "Nombre - email".',
    difficulty: 'fácil',
    type: 'write',
    hint: "Usa || ' - ' || para concatenar en SQLite, o CONCAT en MySQL.",
    starterCode: '-- Combina nombre y email\nSELECT ',
    validationQuery: "SELECT name || ' - ' || email AS info FROM Customers",
    expectedCheck: arraysMatch,
    category: 'SELECT',
  },
  {
    id: 15,
    title: 'Seleccionar con LIMIT y OFFSET',
    description: 'Muestra el nombre y precio de los productos del 6° al 10° registro (paginación).',
    difficulty: 'fácil',
    type: 'write',
    hint: 'LIMIT 5 OFFSET 5 salta los primeros 5 registros y devuelve los siguientes 5.',
    starterCode: '-- Página 2 de productos (5 por página)\nSELECT ',
    validationQuery: 'SELECT title, price FROM Products LIMIT 5 OFFSET 5',
    expectedCheck: arraysMatch,
    category: 'SELECT',
  },

  // ── WHERE ─────────────────────────────────────────────────────────────────

  {
    id: 16,
    title: 'Filtrar con BETWEEN',
    description: 'Lista los productos cuyo precio esté entre 20 y 100 (inclusive). Muestra título y precio.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'BETWEEN incluye los límites del rango.',
    starterCode: '-- Productos entre 20 y 100\nSELECT ',
    validationQuery: 'SELECT title, price FROM Products WHERE price BETWEEN 20 AND 100',
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 17,
    title: 'Filtrar con LIKE',
    description: "Encuentra todos los clientes cuyo nombre empieza con la letra 'M'. Muestra nombre y email.",
    difficulty: 'fácil',
    type: 'write',
    hint: "El patrón 'M%' con LIKE busca nombres que empiezan con M.",
    starterCode: "-- Clientes cuyo nombre empieza con 'M'\nSELECT ",
    validationQuery: "SELECT name, email FROM Customers WHERE name LIKE 'M%'",
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 18,
    title: 'Filtrar con IN',
    description: "Muestra los empleados que trabajan en los departamentos con id 1, 3 o 5.",
    difficulty: 'fácil',
    type: 'write',
    hint: 'IN acepta una lista de valores separados por coma.',
    starterCode: '-- Empleados de departamentos 1, 3 o 5\nSELECT ',
    validationQuery: 'SELECT name, department_id FROM Employees WHERE department_id IN (1, 3, 5)',
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 19,
    title: 'Valores NULL',
    description: 'Encuentra los empleados que NO tienen email registrado (valor NULL).',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Para buscar NULL se usa IS NULL, no = NULL.',
    starterCode: '-- Empleados sin email\nSELECT ',
    validationQuery: 'SELECT name FROM Employees WHERE email IS NULL',
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 20,
    title: 'Arregla el Filtro NULL',
    description: "Esta consulta intenta buscar clientes sin país registrado pero usa = NULL. Corrígela.",
    difficulty: 'fácil',
    type: 'fix',
    hint: 'NULL no se puede comparar con =, usa IS NULL.',
    starterCode: "SELECT name FROM Customers WHERE country = NULL;",
    validationQuery: 'SELECT name FROM Customers WHERE country IS NULL',
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 21,
    title: 'NOT IN',
    description: "Muestra los productos que NO pertenecen a las categorías 'Electronics' ni 'Books'.",
    difficulty: 'medio',
    type: 'write',
    hint: 'NOT IN excluye los valores de la lista.',
    starterCode: '-- Productos fuera de ciertas categorías\nSELECT ',
    validationQuery: "SELECT title, category FROM Products WHERE category NOT IN ('Electronics', 'Books')",
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },
  {
    id: 22,
    title: 'Completa el WHERE compuesto',
    description: "Completa la consulta para obtener clientes de 'México' o 'España' que tengan email registrado.",
    difficulty: 'medio',
    type: 'complete',
    hint: 'Combina OR con AND y IS NOT NULL.',
    starterCode: "SELECT name, email, country\nFROM Customers\nWHERE ___",
    validationQuery: "SELECT name, email, country FROM Customers WHERE (country = 'México' OR country = 'España') AND email IS NOT NULL",
    expectedCheck: arraysMatch,
    category: 'WHERE',
  },

  // ── ORDER BY ──────────────────────────────────────────────────────────────

  {
    id: 23,
    title: 'Ordenar por Múltiples Columnas',
    description: 'Lista todos los empleados ordenados primero por departamento (ASC) y luego por salario (DESC).',
    difficulty: 'fácil',
    type: 'write',
    hint: 'ORDER BY acepta varias columnas separadas por coma.',
    starterCode: '-- Orden múltiple\nSELECT ',
    validationQuery: 'SELECT name, department_id, salary FROM Employees ORDER BY department_id ASC, salary DESC',
    expectedCheck: arraysMatch,
    category: 'ORDER BY',
  },
  {
    id: 24,
    title: 'Arregla el ORDER BY',
    description: 'La consulta tiene un error en la cláusula de ordenación. Corrígela para que devuelva los clientes ordenados por nombre ascendente.',
    difficulty: 'fácil',
    type: 'fix',
    hint: 'La cláusula ORDER BY va al final, después de WHERE.',
    starterCode: "SELECT name, country FROM Customers ORDER name ASC;",
    validationQuery: 'SELECT name, country FROM Customers ORDER BY name ASC',
    expectedCheck: arraysMatch,
    category: 'ORDER BY',
  },
  {
    id: 25,
    title: 'Top 5 Empleados Mejor Pagados',
    description: 'Obtén los 5 empleados con mayor salario. Muestra nombre y salario.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'ORDER BY salary DESC LIMIT 5.',
    starterCode: '-- Top 5 sueldos\nSELECT ',
    validationQuery: 'SELECT name, salary FROM Employees ORDER BY salary DESC LIMIT 5',
    expectedCheck: arraysMatch,
    category: 'ORDER BY',
  },

  // ── Funciones de agregación ───────────────────────────────────────────────

  {
    id: 26,
    title: 'Contar Registros',
    description: 'Cuenta el total de clientes registrados en la base de datos. Llama al resultado "total_clientes".',
    difficulty: 'fácil',
    type: 'write',
    hint: 'COUNT(*) cuenta todas las filas.',
    starterCode: '-- Total de clientes\nSELECT ',
    validationQuery: 'SELECT COUNT(*) AS total_clientes FROM Customers',
    expectedCheck: countMatch,
    category: 'Agregación',
  },
  {
    id: 27,
    title: 'Salario Promedio',
    description: 'Calcula el salario promedio de todos los empleados. Llama al resultado "salario_promedio".',
    difficulty: 'fácil',
    type: 'write',
    hint: 'AVG() calcula el promedio de una columna numérica.',
    starterCode: '-- Salario promedio\nSELECT ',
    validationQuery: 'SELECT AVG(salary) AS salario_promedio FROM Employees',
    expectedCheck: countMatch,
    category: 'Agregación',
  },
  {
    id: 28,
    title: 'Precio Máximo y Mínimo',
    description: 'Muestra el precio más alto y el más bajo de todos los productos.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'Usa MAX() y MIN() en la misma consulta.',
    starterCode: '-- Precio máximo y mínimo\nSELECT ',
    validationQuery: 'SELECT MAX(price) AS precio_max, MIN(price) AS precio_min FROM Products',
    expectedCheck: arraysMatch,
    category: 'Agregación',
  },
  {
    id: 29,
    title: 'Suma Total de Pedidos',
    description: 'Calcula el total de ingresos sumando todos los valores de la columna total en Orders.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'SUM() suma todos los valores de una columna.',
    starterCode: '-- Ingresos totales\nSELECT ',
    validationQuery: 'SELECT SUM(total) AS ingresos_totales FROM Orders',
    expectedCheck: countMatch,
    category: 'Agregación',
  },
  {
    id: 30,
    title: 'Completa el GROUP BY',
    description: 'Completa la consulta para contar cuántos productos hay en cada categoría.',
    difficulty: 'medio',
    type: 'complete',
    hint: 'GROUP BY agrupa los resultados por un campo.',
    starterCode: 'SELECT category, COUNT(*) AS total\nFROM Products\nGROUP BY ___',
    validationQuery: 'SELECT category, COUNT(*) AS total FROM Products GROUP BY category',
    expectedCheck: arraysMatch,
    category: 'GROUP BY',
  },
  {
    id: 31,
    title: 'Salario Máximo por Departamento',
    description: 'Muestra el salario máximo de cada departamento. Incluye el department_id y el máximo salario.',
    difficulty: 'medio',
    type: 'write',
    hint: 'Combina MAX() con GROUP BY department_id.',
    starterCode: '-- Salario máximo por depto\nSELECT ',
    validationQuery: 'SELECT department_id, MAX(salary) AS salario_max FROM Employees GROUP BY department_id',
    expectedCheck: arraysMatch,
    category: 'GROUP BY',
  },
  {
    id: 32,
    title: 'HAVING: Departamentos Grandes',
    description: 'Muestra solo los departamentos que tienen más de 3 empleados. Incluye el department_id y el conteo.',
    difficulty: 'medio',
    type: 'write',
    hint: 'HAVING filtra después de agrupar, a diferencia de WHERE.',
    starterCode: '-- Departamentos con más de 3 empleados\nSELECT ',
    validationQuery: 'SELECT department_id, COUNT(*) AS total FROM Employees GROUP BY department_id HAVING COUNT(*) > 3',
    expectedCheck: arraysMatch,
    category: 'HAVING',
  },
  {
    id: 33,
    title: 'Arregla el HAVING',
    description: 'La consulta usa WHERE para filtrar una función de agregación. Corrígela.',
    difficulty: 'medio',
    type: 'fix',
    hint: 'WHERE no puede usarse con funciones de agregación como SUM(). Usa HAVING.',
    starterCode: 'SELECT customer_id, SUM(total) AS gasto\nFROM Orders\nGROUP BY customer_id\nWHERE SUM(total) > 300;',
    validationQuery: 'SELECT customer_id, SUM(total) AS gasto FROM Orders GROUP BY customer_id HAVING SUM(total) > 300',
    expectedCheck: arraysMatch,
    category: 'HAVING',
  },
  {
    id: 34,
    title: 'Promedio de Pedidos por Cliente',
    description: 'Calcula el promedio de gasto por pedido de cada cliente. Muestra customer_id y el promedio.',
    difficulty: 'medio',
    type: 'write',
    hint: 'Usa AVG(total) con GROUP BY customer_id.',
    starterCode: '-- Promedio de gasto por cliente\nSELECT ',
    validationQuery: 'SELECT customer_id, AVG(total) AS promedio FROM Orders GROUP BY customer_id',
    expectedCheck: arraysMatch,
    category: 'GROUP BY',
  },

  // ── JOIN ──────────────────────────────────────────────────────────────────

  {
    id: 35,
    title: 'Completa el INNER JOIN',
    description: 'Completa la consulta para unir Orders con Customers y mostrar el nombre del cliente y el total del pedido.',
    difficulty: 'fácil',
    type: 'complete',
    hint: 'ON define la condición de unión entre las dos tablas.',
    starterCode: 'SELECT c.name, o.total\nFROM Orders o\nINNER JOIN Customers c ON ___',
    validationQuery: 'SELECT c.name, o.total FROM Orders o INNER JOIN Customers c ON o.customer_id = c.id',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 36,
    title: 'Productos sin Pedidos',
    description: 'Usa un LEFT JOIN para encontrar los productos que nunca han sido pedidos.',
    difficulty: 'medio',
    type: 'write',
    hint: 'LEFT JOIN + WHERE o.product_id IS NULL.',
    starterCode: '-- Productos sin pedidos\nSELECT ',
    validationQuery: 'SELECT p.title FROM Products p LEFT JOIN Orders o ON p.id = o.product_id WHERE o.id IS NULL',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 37,
    title: 'Departamentos sin Empleados',
    description: 'Muestra los departamentos que no tienen ningún empleado asignado.',
    difficulty: 'medio',
    type: 'write',
    hint: 'LEFT JOIN desde Departments hacia Employees y filtra con IS NULL.',
    starterCode: '-- Departamentos vacíos\nSELECT ',
    validationQuery: 'SELECT d.department_name FROM Departments d LEFT JOIN Employees e ON d.id = e.department_id WHERE e.id IS NULL',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 38,
    title: 'JOIN con Filtro',
    description: "Une empleados con departamentos y muestra solo los del departamento 'Engineering'.",
    difficulty: 'medio',
    type: 'write',
    hint: 'Puedes filtrar por d.department_name en el WHERE después del JOIN.',
    starterCode: "-- Solo empleados de Engineering\nSELECT ",
    validationQuery: "SELECT e.name, d.department_name FROM Employees e INNER JOIN Departments d ON e.department_id = d.id WHERE d.department_name = 'Engineering'",
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 39,
    title: 'Arregla el JOIN',
    description: 'La condición ON del JOIN está mal escrita. Corrígela para unir correctamente Orders con Products.',
    difficulty: 'medio',
    type: 'fix',
    hint: 'La columna que une Orders con Products es product_id.',
    starterCode: 'SELECT o.id, p.title\nFROM Orders o\nINNER JOIN Products p ON o.id = p.id;',
    validationQuery: 'SELECT o.id, p.title FROM Orders o INNER JOIN Products p ON o.product_id = p.id',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 40,
    title: 'SELF JOIN: Empleado y su Jefe',
    description: 'Muestra el nombre de cada empleado junto al nombre de su jefe (manager). Usa un SELF JOIN sobre la tabla Employees.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Une Employees e1 con Employees e2 usando e1.manager_id = e2.id.',
    starterCode: '-- Empleado y su jefe\nSELECT ',
    validationQuery: 'SELECT e1.name AS empleado, e2.name AS jefe FROM Employees e1 LEFT JOIN Employees e2 ON e1.manager_id = e2.id',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },
  {
    id: 41,
    title: 'Triple JOIN',
    description: 'Lista el nombre del cliente, el producto comprado y el nombre del departamento del empleado que procesó el pedido.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Necesitas unir Orders → Customers, Orders → Products y Orders → Employees → Departments.',
    starterCode: '-- Triple join: cliente, producto, departamento\nSELECT ',
    validationQuery: 'SELECT c.name, p.title, d.department_name FROM Orders o INNER JOIN Customers c ON o.customer_id = c.id INNER JOIN Products p ON o.product_id = p.id INNER JOIN Employees e ON o.employee_id = e.id INNER JOIN Departments d ON e.department_id = d.id',
    expectedCheck: arraysMatch,
    category: 'Multi-JOIN',
  },
  {
    id: 42,
    title: 'Completa el LEFT JOIN',
    description: 'Completa la consulta para mostrar todos los clientes y, si tienen pedidos, el total gastado.',
    difficulty: 'medio',
    type: 'complete',
    hint: 'LEFT JOIN garantiza que aparezcan todos los clientes, aunque no tengan pedidos.',
    starterCode: 'SELECT c.name, SUM(o.total) AS total_gastado\nFROM Customers c\nLEFT JOIN Orders o ON ___\nGROUP BY c.name',
    validationQuery: 'SELECT c.name, SUM(o.total) AS total_gastado FROM Customers c LEFT JOIN Orders o ON c.id = o.customer_id GROUP BY c.name',
    expectedCheck: arraysMatch,
    category: 'JOIN',
  },

  // ── Subqueries ────────────────────────────────────────────────────────────

  {
    id: 43,
    title: 'Subquery en WHERE',
    description: 'Muestra los empleados cuyo salario es mayor que el salario promedio de todos los empleados.',
    difficulty: 'medio',
    type: 'write',
    hint: 'Usa (SELECT AVG(salary) FROM Employees) como subquery en el WHERE.',
    starterCode: '-- Empleados por encima del promedio\nSELECT ',
    validationQuery: 'SELECT name, salary FROM Employees WHERE salary > (SELECT AVG(salary) FROM Employees)',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 44,
    title: 'Subquery con IN',
    description: "Muestra los clientes que han realizado al menos un pedido con total mayor a 500.",
    difficulty: 'medio',
    type: 'write',
    hint: 'Usa IN con una subconsulta que devuelva customer_id de Orders donde total > 500.',
    starterCode: '-- Clientes con pedidos grandes\nSELECT ',
    validationQuery: 'SELECT name, email FROM Customers WHERE id IN (SELECT customer_id FROM Orders WHERE total > 500)',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 45,
    title: 'Subquery Correlacionada',
    description: 'Para cada departamento, muestra su nombre y el nombre del empleado mejor pagado dentro de ese departamento.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa una subconsulta correlacionada que referencie el department_id del SELECT externo.',
    starterCode: '-- Empleado mejor pagado por depto\nSELECT ',
    validationQuery: 'SELECT d.department_name, (SELECT e.name FROM Employees e WHERE e.department_id = d.id ORDER BY e.salary DESC LIMIT 1) AS top_empleado FROM Departments d',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 46,
    title: 'EXISTS',
    description: 'Lista los clientes que tienen al menos un pedido registrado usando EXISTS.',
    difficulty: 'medio',
    type: 'write',
    hint: 'EXISTS devuelve true si la subconsulta retorna al menos una fila.',
    starterCode: '-- Clientes con pedidos (EXISTS)\nSELECT ',
    validationQuery: 'SELECT name FROM Customers c WHERE EXISTS (SELECT 1 FROM Orders o WHERE o.customer_id = c.id)',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 47,
    title: 'Subquery en FROM',
    description: 'Usa una subconsulta en el FROM para calcular el gasto total por cliente y luego filtra los que gastaron más de 200.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'La subconsulta actúa como una tabla temporal; dale un alias.',
    starterCode: '-- Subquery como tabla temporal\nSELECT ',
    validationQuery: 'SELECT sub.customer_id, sub.gasto FROM (SELECT customer_id, SUM(total) AS gasto FROM Orders GROUP BY customer_id) AS sub WHERE sub.gasto > 200',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 48,
    title: 'Arregla el NOT IN',
    description: 'La subconsulta de NOT IN puede devolver NULL, lo que hace que no retorne resultados. Corrígela.',
    difficulty: 'difícil',
    type: 'fix',
    hint: 'Cuando la subconsulta puede devolver NULL, NOT IN falla. Agrega WHERE customer_id IS NOT NULL.',
    starterCode: 'SELECT name FROM Customers\nWHERE id NOT IN (SELECT customer_id FROM Orders);',
    validationQuery: 'SELECT name FROM Customers WHERE id NOT IN (SELECT customer_id FROM Orders WHERE customer_id IS NOT NULL)',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },

  // ── CASE y expresiones ────────────────────────────────────────────────────

  {
    id: 49,
    title: 'CASE Simple',
    description: "Clasifica a los empleados por salario: menos de 40000 = 'Junior', entre 40000 y 70000 = 'Mid', más de 70000 = 'Senior'. Muestra nombre, salario y la clasificación.",
    difficulty: 'medio',
    type: 'write',
    hint: 'Usa CASE WHEN ... THEN ... ELSE ... END.',
    starterCode: '-- Clasificación de empleados\nSELECT ',
    validationQuery: "SELECT name, salary, CASE WHEN salary < 40000 THEN 'Junior' WHEN salary BETWEEN 40000 AND 70000 THEN 'Mid' ELSE 'Senior' END AS nivel FROM Employees",
    expectedCheck: arraysMatch,
    category: 'CASE',
  },
  {
    id: 50,
    title: 'CASE en ORDER BY',
    description: "Ordena los pedidos mostrando primero los de estado 'PENDING', luego 'PROCESSING' y finalmente 'DELIVERED'. Muestra id y status.",
    difficulty: 'difícil',
    type: 'write',
    hint: 'Puedes usar CASE directamente dentro de ORDER BY para definir un orden personalizado.',
    starterCode: '-- Orden personalizado con CASE\nSELECT ',
    validationQuery: "SELECT id, status FROM Orders ORDER BY CASE status WHEN 'PENDING' THEN 1 WHEN 'PROCESSING' THEN 2 ELSE 3 END",
    expectedCheck: arraysMatch,
    category: 'CASE',
  },
  {
    id: 51,
    title: 'Completa el CASE',
    description: "Completa el CASE para etiquetar productos: precio < 10 = 'Barato', precio entre 10 y 50 = 'Normal', precio > 50 = 'Caro'.",
    difficulty: 'medio',
    type: 'complete',
    hint: 'Recuerda cerrar el CASE con END y darle un alias.',
    starterCode: "SELECT title, price,\n  CASE\n    WHEN price < 10 THEN 'Barato'\n    ___\n    ELSE 'Caro'\n  END AS rango_precio\nFROM Products",
    validationQuery: "SELECT title, price, CASE WHEN price < 10 THEN 'Barato' WHEN price BETWEEN 10 AND 50 THEN 'Normal' ELSE 'Caro' END AS rango_precio FROM Products",
    expectedCheck: arraysMatch,
    category: 'CASE',
  },
  {
    id: 52,
    title: 'SUM con CASE (Pivot)',
    description: 'Cuenta cuántos empleados son ACTIVE y cuántos INACTIVE en una sola fila usando SUM + CASE.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'SUM(CASE WHEN status = X THEN 1 ELSE 0 END) es una técnica de pivote.',
    starterCode: '-- Conteo condicional en una fila\nSELECT ',
    validationQuery: "SELECT SUM(CASE WHEN status = 'ACTIVE' THEN 1 ELSE 0 END) AS activos, SUM(CASE WHEN status = 'INACTIVE' THEN 1 ELSE 0 END) AS inactivos FROM Employees",
    expectedCheck: arraysMatch,
    category: 'CASE',
  },

  // ── Funciones de texto y fecha ────────────────────────────────────────────

  {
    id: 53,
    title: 'UPPER y LOWER',
    description: 'Muestra el nombre de todos los clientes en mayúsculas y su email en minúsculas.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'UPPER() convierte a mayúsculas, LOWER() a minúsculas.',
    starterCode: '-- Nombre en mayúsculas, email en minúsculas\nSELECT ',
    validationQuery: 'SELECT UPPER(name) AS nombre, LOWER(email) AS email FROM Customers',
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 54,
    title: 'LENGTH',
    description: 'Muestra el nombre de los productos y la longitud (número de caracteres) de su título. Llama al resultado "longitud".',
    difficulty: 'fácil',
    type: 'write',
    hint: 'LENGTH() devuelve el número de caracteres de una cadena.',
    starterCode: '-- Longitud del título\nSELECT ',
    validationQuery: 'SELECT title, LENGTH(title) AS longitud FROM Products',
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 55,
    title: 'SUBSTR',
    description: 'Muestra los primeros 3 caracteres del nombre de cada departamento como abreviatura.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'SUBSTR(columna, inicio, longitud) en SQLite, SUBSTRING en otros motores.',
    starterCode: '-- Abreviatura del departamento\nSELECT ',
    validationQuery: 'SELECT department_name, SUBSTR(department_name, 1, 3) AS abrev FROM Departments',
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 56,
    title: 'ROUND',
    description: 'Muestra el precio de cada producto redondeado a 1 decimal.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'ROUND(columna, decimales) redondea al número de decimales indicado.',
    starterCode: '-- Precio redondeado\nSELECT ',
    validationQuery: 'SELECT title, ROUND(price, 1) AS precio_redondeado FROM Products',
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 57,
    title: 'Año del Pedido',
    description: 'Muestra el id de cada pedido y el año en que fue realizado, extraído de la columna order_date.',
    difficulty: 'medio',
    type: 'write',
    hint: 'STRFTIME en SQLite: strftime(\'%Y\', columna_fecha). En MySQL: YEAR(columna_fecha).',
    starterCode: '-- Año del pedido\nSELECT ',
    validationQuery: "SELECT id, strftime('%Y', order_date) AS anio FROM Orders",
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 58,
    title: 'Pedidos de Este Mes',
    description: 'Muestra los pedidos realizados en el mes actual. Muestra id y order_date.',
    difficulty: 'medio',
    type: 'write',
    hint: "En SQLite usa strftime('%Y-%m', order_date) = strftime('%Y-%m', 'now').",
    starterCode: '-- Pedidos del mes actual\nSELECT ',
    validationQuery: "SELECT id, order_date FROM Orders WHERE strftime('%Y-%m', order_date) = strftime('%Y-%m', 'now')",
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 59,
    title: 'COALESCE',
    description: "Muestra el nombre de cada cliente y su teléfono. Si el teléfono es NULL, muestra 'Sin teléfono'.",
    difficulty: 'medio',
    type: 'write',
    hint: 'COALESCE devuelve el primer valor no NULL de la lista.',
    starterCode: "-- Teléfono o valor por defecto\nSELECT ",
    validationQuery: "SELECT name, COALESCE(phone, 'Sin teléfono') AS telefono FROM Customers",
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },
  {
    id: 60,
    title: 'Completa con REPLACE',
    description: "Completa la consulta para mostrar los emails de los clientes reemplazando '@' por ' [at] '.",
    difficulty: 'medio',
    type: 'complete',
    hint: "REPLACE(columna, valor_buscado, valor_nuevo).",
    starterCode: "SELECT name, REPLACE(email, ___, ___) AS email_seguro\nFROM Customers",
    validationQuery: "SELECT name, REPLACE(email, '@', ' [at] ') AS email_seguro FROM Customers",
    expectedCheck: arraysMatch,
    category: 'Funciones',
  },

  // ── CTE (WITH) ────────────────────────────────────────────────────────────

  {
    id: 61,
    title: 'CTE Básica',
    description: 'Usa una CTE llamada "empleados_activos" para obtener los empleados con status ACTIVE y luego selecciona su nombre y salario.',
    difficulty: 'medio',
    type: 'write',
    hint: 'WITH nombre_cte AS (SELECT ...) SELECT ... FROM nombre_cte.',
    starterCode: '-- CTE básica\nWITH ',
    validationQuery: "WITH empleados_activos AS (SELECT name, salary FROM Employees WHERE status = 'ACTIVE') SELECT name, salary FROM empleados_activos",
    expectedCheck: arraysMatch,
    category: 'CTE',
  },
  {
    id: 62,
    title: 'CTE con Agregación',
    description: 'Usa una CTE para calcular el total de ventas por cliente y luego muestra solo los clientes cuyo total supera 1000.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'La CTE hace el GROUP BY + SUM, el SELECT exterior aplica el filtro.',
    starterCode: '-- CTE con filtro posterior\nWITH ',
    validationQuery: 'WITH ventas AS (SELECT customer_id, SUM(total) AS total_ventas FROM Orders GROUP BY customer_id) SELECT customer_id, total_ventas FROM ventas WHERE total_ventas > 1000',
    expectedCheck: arraysMatch,
    category: 'CTE',
  },
  {
    id: 63,
    title: 'Completa la CTE',
    description: 'Completa la CTE para obtener el producto más caro de cada categoría y luego listar esos productos.',
    difficulty: 'difícil',
    type: 'complete',
    hint: 'La CTE necesita MAX(price) GROUP BY category.',
    starterCode: 'WITH max_precio AS (\n  SELECT category, ___ AS precio_max\n  FROM Products\n  GROUP BY category\n)\nSELECT p.title, p.category, p.price\nFROM Products p\nINNER JOIN max_precio m ON p.category = m.category AND p.price = m.precio_max',
    validationQuery: 'WITH max_precio AS (SELECT category, MAX(price) AS precio_max FROM Products GROUP BY category) SELECT p.title, p.category, p.price FROM Products p INNER JOIN max_precio m ON p.category = m.category AND p.price = m.precio_max',
    expectedCheck: arraysMatch,
    category: 'CTE',
  },
  {
    id: 64,
    title: 'CTE Múltiple',
    description: 'Define dos CTEs: "top_clientes" (clientes con más de 3 pedidos) y "productos_caros" (precio > 100). Luego muestra los pedidos donde coincidan ambos.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Separa las CTEs con coma: WITH cte1 AS (...), cte2 AS (...) SELECT ...',
    starterCode: '-- Múltiples CTEs\nWITH ',
    validationQuery: 'WITH top_clientes AS (SELECT customer_id FROM Orders GROUP BY customer_id HAVING COUNT(*) > 3), productos_caros AS (SELECT id FROM Products WHERE price > 100) SELECT o.id, o.customer_id, o.product_id FROM Orders o INNER JOIN top_clientes tc ON o.customer_id = tc.customer_id INNER JOIN productos_caros pc ON o.product_id = pc.id',
    expectedCheck: arraysMatch,
    category: 'CTE',
  },

  // ── Window functions ──────────────────────────────────────────────────────

  {
    id: 65,
    title: 'ROW_NUMBER',
    description: 'Asigna un número de fila a cada empleado ordenados por salario descendente. Muestra nombre, salario y el número de fila.',
    difficulty: 'medio',
    type: 'write',
    hint: 'ROW_NUMBER() OVER (ORDER BY salary DESC)',
    starterCode: '-- Número de fila por salario\nSELECT ',
    validationQuery: 'SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS fila FROM Employees',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 66,
    title: 'RANK por Departamento',
    description: 'Asigna un ranking de salario dentro de cada departamento. Muestra nombre, department_id, salario y el ranking.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'RANK() OVER (PARTITION BY department_id ORDER BY salary DESC)',
    starterCode: '-- Ranking dentro de cada departamento\nSELECT ',
    validationQuery: 'SELECT name, department_id, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS ranking FROM Employees',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 67,
    title: 'SUM acumulado',
    description: 'Muestra cada pedido con su total y el total acumulado de todos los pedidos hasta ese punto, ordenado por id.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'SUM(total) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)',
    starterCode: '-- Total acumulado\nSELECT ',
    validationQuery: 'SELECT id, total, SUM(total) OVER (ORDER BY id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS total_acumulado FROM Orders',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 68,
    title: 'Completa el PARTITION BY',
    description: 'Completa la función de ventana para calcular el salario promedio dentro de cada departamento.',
    difficulty: 'difícil',
    type: 'complete',
    hint: 'AVG(salary) OVER (PARTITION BY ...)',
    starterCode: 'SELECT name, department_id, salary,\n  AVG(salary) OVER (PARTITION BY ___) AS prom_depto\nFROM Employees',
    validationQuery: 'SELECT name, department_id, salary, AVG(salary) OVER (PARTITION BY department_id) AS prom_depto FROM Employees',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 69,
    title: 'LAG: Pedido Anterior',
    description: 'Muestra cada pedido con su total y el total del pedido anterior del mismo cliente. Usa LAG.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'LAG(total, 1) OVER (PARTITION BY customer_id ORDER BY id)',
    starterCode: '-- Total del pedido anterior\nSELECT ',
    validationQuery: 'SELECT id, customer_id, total, LAG(total, 1) OVER (PARTITION BY customer_id ORDER BY id) AS pedido_anterior FROM Orders',
    expectedCheck: arraysMatch,
    category: 'Window',
  },

  // ── Operadores Set ────────────────────────────────────────────────────────

  {
    id: 70,
    title: 'UNION de Ciudades',
    description: 'Muestra una lista única de todas las ciudades que aparecen tanto en Customers como en Suppliers (tabla de proveedores).',
    difficulty: 'medio',
    type: 'write',
    hint: 'UNION elimina duplicados automáticamente.',
    starterCode: '-- Ciudades únicas entre clientes y proveedores\nSELECT ',
    validationQuery: 'SELECT city FROM Customers UNION SELECT city FROM Suppliers',
    expectedCheck: arraysMatch,
    category: 'Set Ops',
  },
  {
    id: 71,
    title: 'UNION ALL',
    description: 'Combina los nombres de Employees y Customers en una sola lista incluyendo duplicados.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'UNION ALL no elimina duplicados y es más eficiente.',
    starterCode: '-- Todos los nombres (con duplicados)\nSELECT ',
    validationQuery: 'SELECT name FROM Employees UNION ALL SELECT name FROM Customers',
    expectedCheck: arraysMatch,
    category: 'Set Ops',
  },
  {
    id: 72,
    title: 'INTERSECT',
    description: 'Encuentra las ciudades que tienen tanto clientes como proveedores registrados.',
    difficulty: 'medio',
    type: 'write',
    hint: 'INTERSECT devuelve solo las filas que están en ambos conjuntos.',
    starterCode: '-- Ciudades con clientes Y proveedores\nSELECT ',
    validationQuery: 'SELECT city FROM Customers INTERSECT SELECT city FROM Suppliers',
    expectedCheck: arraysMatch,
    category: 'Set Ops',
  },
  {
    id: 73,
    title: 'EXCEPT',
    description: 'Muestra las ciudades donde hay clientes pero NO hay proveedores.',
    difficulty: 'medio',
    type: 'write',
    hint: 'EXCEPT devuelve las filas del primer SELECT que no están en el segundo.',
    starterCode: '-- Ciudades solo con clientes\nSELECT ',
    validationQuery: 'SELECT city FROM Customers EXCEPT SELECT city FROM Suppliers',
    expectedCheck: arraysMatch,
    category: 'Set Ops',
  },
  {
    id: 74,
    title: 'Arregla el UNION',
    description: 'El UNION falla porque las columnas seleccionadas no coinciden en número. Corrígelo.',
    difficulty: 'medio',
    type: 'fix',
    hint: 'Ambos SELECT en un UNION deben tener el mismo número de columnas.',
    starterCode: 'SELECT name, email FROM Customers\nUNION\nSELECT name FROM Suppliers;',
    validationQuery: 'SELECT name, email FROM Customers UNION SELECT name, email FROM Suppliers',
    expectedCheck: arraysMatch,
    category: 'Set Ops',
  },

  // ── DDL ───────────────────────────────────────────────────────────────────

  {
    id: 75,
    title: 'Crear Tabla',
    description: 'Crea una tabla llamada "Reviews" con las columnas: id (INTEGER, PK), product_id (INTEGER), rating (INTEGER), comment (TEXT) y created_at (TEXT).',
    difficulty: 'medio',
    type: 'write',
    hint: 'CREATE TABLE nombre (col tipo restricción, ...)',
    starterCode: '-- Crea la tabla Reviews\nCREATE TABLE ',
    validationQuery: 'CREATE TABLE IF NOT EXISTS Reviews (id INTEGER PRIMARY KEY, product_id INTEGER, rating INTEGER, comment TEXT, created_at TEXT)',
    expectedCheck: () => true,
    category: 'DDL',
  },
  {
    id: 76,
    title: 'ALTER TABLE: Agregar Columna',
    description: 'Agrega una columna llamada "phone" de tipo TEXT a la tabla Customers.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'ALTER TABLE nombre ADD COLUMN col tipo.',
    starterCode: '-- Agregar columna phone\nALTER TABLE ',
    validationQuery: 'ALTER TABLE Customers ADD COLUMN phone TEXT',
    expectedCheck: () => true,
    category: 'DDL',
  },
  {
    id: 77,
    title: 'Arregla el CREATE TABLE',
    description: 'El CREATE TABLE tiene errores de sintaxis. Corrígelo.',
    difficulty: 'medio',
    type: 'fix',
    hint: 'Verifica los tipos de datos y la sintaxis de PRIMARY KEY.',
    starterCode: 'CREATE TABLE Orders (\n  id INTEGER PRIMARY,\n  customer_id INT\n  total DECIMAL,\n  order_date TEXT\n);',
    validationQuery: 'CREATE TABLE IF NOT EXISTS Orders (id INTEGER PRIMARY KEY, customer_id INT, total DECIMAL, order_date TEXT)',
    expectedCheck: () => true,
    category: 'DDL',
  },
  {
    id: 78,
    title: 'CREATE INDEX',
    description: 'Crea un índice llamado "idx_customer_email" sobre la columna email de la tabla Customers.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'CREATE INDEX nombre ON tabla (columna).',
    starterCode: '-- Crea el índice\nCREATE INDEX ',
    validationQuery: 'CREATE INDEX idx_customer_email ON Customers (email)',
    expectedCheck: () => true,
    category: 'DDL',
  },

  // ── INSERT / UPDATE / DELETE ──────────────────────────────────────────────

  {
    id: 79,
    title: 'INSERT Múltiple',
    description: 'Inserta 3 productos en la tabla Products en una sola sentencia: ("Laptop", 999.99, "Electronics"), ("Mouse", 29.99, "Electronics"), ("Desk", 149.99, "Furniture").',
    difficulty: 'medio',
    type: 'write',
    hint: 'INSERT INTO tabla (cols) VALUES (row1), (row2), (row3).',
    starterCode: '-- Insertar múltiples filas\nINSERT INTO Products ',
    validationQuery: "INSERT INTO Products (title, price, category) VALUES ('Laptop', 999.99, 'Electronics'), ('Mouse', 29.99, 'Electronics'), ('Desk', 149.99, 'Furniture')",
    expectedCheck: () => true,
    category: 'DML',
  },
  {
    id: 80,
    title: 'UPDATE con Subquery',
    description: 'Aplica un aumento del 10% de salario a todos los empleados del departamento de "Engineering".',
    difficulty: 'difícil',
    type: 'write',
    hint: "UPDATE Employees SET salary = salary * 1.1 WHERE department_id = (SELECT id FROM Departments WHERE department_name = 'Engineering').",
    starterCode: '-- Aumento del 10% en Engineering\nUPDATE ',
    validationQuery: "UPDATE Employees SET salary = salary * 1.1 WHERE department_id = (SELECT id FROM Departments WHERE department_name = 'Engineering')",
    expectedCheck: () => true,
    category: 'DML',
  },
  {
    id: 81,
    title: 'DELETE Condicional',
    description: 'Elimina todos los pedidos con total igual a 0.',
    difficulty: 'fácil',
    type: 'write',
    hint: 'DELETE FROM tabla WHERE condicion.',
    starterCode: '-- Eliminar pedidos sin valor\nDELETE ',
    validationQuery: 'DELETE FROM Orders WHERE total = 0',
    expectedCheck: () => true,
    category: 'DML',
  },
  {
    id: 82,
    title: 'Arregla el UPDATE',
    description: 'El UPDATE intenta modificar todos los registros sin querer (falta el WHERE). Corrígelo para actualizar solo el cliente con id = 5.',
    difficulty: 'medio',
    type: 'fix',
    hint: 'Sin WHERE, UPDATE afecta a todas las filas. Agrega WHERE id = 5.',
    starterCode: "UPDATE Customers\nSET country = 'Argentina';",
    validationQuery: "UPDATE Customers SET country = 'Argentina' WHERE id = 5",
    expectedCheck: () => true,
    category: 'DML',
  },
  {
    id: 83,
    title: 'INSERT con SELECT',
    description: 'Inserta en la tabla "ArchivoEmpleados" todos los empleados con status INACTIVE de la tabla Employees.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'INSERT INTO tabla SELECT ... FROM ... WHERE ... es válido en SQL.',
    starterCode: '-- Archivar empleados inactivos\nINSERT INTO ArchivoEmpleados ',
    validationQuery: "INSERT INTO ArchivoEmpleados SELECT * FROM Employees WHERE status = 'INACTIVE'",
    expectedCheck: () => true,
    category: 'DML',
  },

  // ── TCL / Transacciones ───────────────────────────────────────────────────

  {
    id: 84,
    title: 'Transacción Básica',
    description: 'Escribe una transacción que transfiera 200 unidades de saldo del cliente con id=1 al cliente con id=2. Si algún UPDATE falla, revierte todo.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'BEGIN; UPDATE ...; UPDATE ...; COMMIT; — y ante error: ROLLBACK.',
    starterCode: '-- Transacción de transferencia\nBEGIN;\n',
    validationQuery: 'BEGIN; UPDATE Customers SET saldo = saldo - 200 WHERE id = 1; UPDATE Customers SET saldo = saldo + 200 WHERE id = 2; COMMIT;',
    expectedCheck: () => true,
    category: 'TCL',
  },
  {
    id: 85,
    title: 'SAVEPOINT',
    description: 'Escribe una transacción con un SAVEPOINT llamado "punto1" entre dos operaciones. Al final haz ROLLBACK al savepoint, no a toda la transacción.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'SAVEPOINT nombre; ... ROLLBACK TO SAVEPOINT nombre;',
    starterCode: '-- Transacción con savepoint\nBEGIN;\n',
    validationQuery: "BEGIN; INSERT INTO Orders (customer_id, total) VALUES (1, 100); SAVEPOINT punto1; INSERT INTO Orders (customer_id, total) VALUES (2, 200); ROLLBACK TO SAVEPOINT punto1; COMMIT;",
    expectedCheck: () => true,
    category: 'TCL',
  },

  // ── Avanzados / Combinados ────────────────────────────────────────────────

  {
    id: 86,
    title: 'Top 1 por Grupo',
    description: 'Muestra el empleado mejor pagado de cada departamento usando ROW_NUMBER y una CTE.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'CTE con ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC), luego filtra WHERE fila = 1.',
    starterCode: '-- El mejor pagado de cada departamento\nWITH ',
    validationQuery: 'WITH ranked AS (SELECT name, department_id, salary, ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS fila FROM Employees) SELECT name, department_id, salary FROM ranked WHERE fila = 1',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 87,
    title: 'Reporte de Ventas Mensual',
    description: "Genera un reporte que muestre el mes, la cantidad de pedidos y el total de ingresos por mes, ordenado cronológicamente.",
    difficulty: 'difícil',
    type: 'write',
    hint: "Extrae el mes con strftime('%Y-%m', order_date) y agrupa por él.",
    starterCode: '-- Reporte mensual de ventas\nSELECT ',
    validationQuery: "SELECT strftime('%Y-%m', order_date) AS mes, COUNT(*) AS num_pedidos, SUM(total) AS ingresos FROM Orders GROUP BY mes ORDER BY mes ASC",
    expectedCheck: arraysMatch,
    category: 'GROUP BY',
  },
  {
    id: 88,
    title: 'Arregla la Consulta Compleja',
    description: 'La siguiente consulta tiene 3 errores: un alias mal usado en WHERE, un GROUP BY faltante y un HAVING incorrecto. Corrígelos.',
    difficulty: 'difícil',
    type: 'fix',
    hint: 'WHERE no puede referenciar alias del SELECT; GROUP BY debe incluir todas las columnas no agregadas.',
    starterCode: "SELECT d.department_name, COUNT(e.id) AS total, AVG(e.salary) AS prom\nFROM Employees e\nJOIN Departments d ON e.department_id = d.id\nWHERE total > 2\nGROUP BY d.id\nHAVING AVG(salary) > 50000;",
    validationQuery: "SELECT d.department_name, COUNT(e.id) AS total, AVG(e.salary) AS prom FROM Employees e JOIN Departments d ON e.department_id = d.id GROUP BY d.id, d.department_name HAVING COUNT(e.id) > 2 AND AVG(e.salary) > 50000",
    expectedCheck: arraysMatch,
    category: 'Debug',
  },
  {
    id: 89,
    title: 'Clientes VIP',
    description: 'Define como cliente VIP a quien: tiene más de 5 pedidos Y ha gastado más de 1000 en total. Lista su nombre, número de pedidos y gasto total.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa GROUP BY + HAVING con dos condiciones unidas por AND.',
    starterCode: '-- Clientes VIP\nSELECT ',
    validationQuery: 'SELECT c.name, COUNT(o.id) AS num_pedidos, SUM(o.total) AS gasto_total FROM Customers c INNER JOIN Orders o ON c.id = o.customer_id GROUP BY c.id, c.name HAVING COUNT(o.id) > 5 AND SUM(o.total) > 1000',
    expectedCheck: arraysMatch,
    category: 'HAVING',
  },
  {
    id: 90,
    title: 'Diferencia entre Salarios',
    description: 'Para cada empleado, muestra su nombre, salario y la diferencia entre su salario y el salario máximo del mismo departamento.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa MAX(salary) OVER (PARTITION BY department_id) como función de ventana.',
    starterCode: '-- Diferencia con el salario máximo del depto\nSELECT ',
    validationQuery: 'SELECT name, salary, MAX(salary) OVER (PARTITION BY department_id) - salary AS diferencia FROM Employees',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 91,
    title: 'Productos más Vendidos',
    description: 'Muestra los 5 productos más vendidos (por cantidad total) junto con su nombre y cantidad total vendida.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa SUM(quantity) con GROUP BY y ORDER BY + LIMIT.',
    starterCode: '-- Top 5 productos más vendidos\nSELECT ',
    validationQuery: 'SELECT p.title, SUM(o.quantity) AS cantidad_total FROM Products p INNER JOIN Orders o ON p.id = o.product_id GROUP BY p.id, p.title ORDER BY cantidad_total DESC LIMIT 5',
    expectedCheck: arraysMatch,
    category: 'Multi-JOIN',
  },
  {
    id: 92,
    title: 'Empleados con Salario Atípico',
    description: 'Muestra los empleados cuyo salario está a más del doble del promedio de su departamento.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Usa AVG en una subconsulta correlacionada o en una CTE.',
    starterCode: '-- Salarios atípicos\nSELECT ',
    validationQuery: 'SELECT e.name, e.salary, e.department_id FROM Employees e WHERE e.salary > 2 * (SELECT AVG(e2.salary) FROM Employees e2 WHERE e2.department_id = e.department_id)',
    expectedCheck: arraysMatch,
    category: 'Subquery',
  },
  {
    id: 93,
    title: 'NTILE: Cuartiles de Precio',
    description: 'Divide los productos en 4 grupos de precio iguales (cuartiles) usando NTILE. Muestra título, precio y el número de cuartil.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'NTILE(4) OVER (ORDER BY price)',
    starterCode: '-- Cuartiles de precio\nSELECT ',
    validationQuery: 'SELECT title, price, NTILE(4) OVER (ORDER BY price) AS cuartil FROM Products',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 94,
    title: 'Completa el DELETE con JOIN',
    description: 'Completa la sentencia para eliminar todos los pedidos de clientes que están bloqueados (blocked = 1).',
    difficulty: 'difícil',
    type: 'complete',
    hint: 'En SQLite usa DELETE con subconsulta; en MySQL se puede hacer con JOIN directo.',
    starterCode: 'DELETE FROM Orders\nWHERE customer_id IN (\n  SELECT id FROM Customers WHERE ___\n)',
    validationQuery: 'DELETE FROM Orders WHERE customer_id IN (SELECT id FROM Customers WHERE blocked = 1)',
    expectedCheck: () => true,
    category: 'DML',
  },
  {
    id: 95,
    title: 'Vista de Resumen',
    description: 'Crea una vista llamada "ResumenVentas" que muestre: nombre del cliente, total de pedidos y suma total gastada.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'CREATE VIEW nombre AS SELECT ...',
    starterCode: '-- Crear vista de resumen\nCREATE VIEW ',
    validationQuery: 'CREATE VIEW ResumenVentas AS SELECT c.name, COUNT(o.id) AS total_pedidos, SUM(o.total) AS total_gastado FROM Customers c LEFT JOIN Orders o ON c.id = o.customer_id GROUP BY c.id, c.name',
    expectedCheck: () => true,
    category: 'DDL',
  },
  {
    id: 96,
    title: 'DENSE_RANK vs RANK',
    description: 'Muestra el nombre y salario de cada empleado con su RANK y DENSE_RANK globales por salario descendente, para ver la diferencia cuando hay empates.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Ambas funciones van en el mismo SELECT: RANK() OVER (...) y DENSE_RANK() OVER (...).',
    starterCode: '-- RANK vs DENSE_RANK\nSELECT ',
    validationQuery: 'SELECT name, salary, RANK() OVER (ORDER BY salary DESC) AS rank_sal, DENSE_RANK() OVER (ORDER BY salary DESC) AS dense_rank_sal FROM Employees',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 97,
    title: 'Porcentaje del Total',
    description: 'Muestra cada pedido con su total y qué porcentaje representa del total global de todos los pedidos. Redondea a 2 decimales.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'SUM(total) OVER () sin PARTITION BY da el total global.',
    starterCode: '-- Porcentaje del total global\nSELECT ',
    validationQuery: 'SELECT id, total, ROUND(total * 100.0 / SUM(total) OVER (), 2) AS porcentaje FROM Orders',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 98,
    title: 'Historial de Cambios con LAG y LEAD',
    description: 'Para cada pedido de un cliente, muestra el total del pedido anterior (LAG) y del siguiente (LEAD), ordenados por fecha.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'LAG(total) OVER (PARTITION BY customer_id ORDER BY order_date) y LEAD(total) OVER (...)',
    starterCode: '-- Pedido anterior y siguiente\nSELECT ',
    validationQuery: 'SELECT id, customer_id, total, LAG(total) OVER (PARTITION BY customer_id ORDER BY order_date) AS anterior, LEAD(total) OVER (PARTITION BY customer_id ORDER BY order_date) AS siguiente FROM Orders',
    expectedCheck: arraysMatch,
    category: 'Window',
  },
  {
    id: 99,
    title: 'Reporte Ejecutivo',
    description: 'Genera un reporte que muestre por departamento: nombre del departamento, número de empleados, salario promedio, salario mínimo y salario máximo. Ordena por salario promedio descendente.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Une Departments con Employees y agrupa por departamento.',
    starterCode: '-- Reporte ejecutivo de departamentos\nSELECT ',
    validationQuery: 'SELECT d.department_name, COUNT(e.id) AS num_empleados, ROUND(AVG(e.salary), 2) AS prom_salario, MIN(e.salary) AS min_salario, MAX(e.salary) AS max_salario FROM Departments d LEFT JOIN Employees e ON d.id = e.department_id GROUP BY d.id, d.department_name ORDER BY prom_salario DESC',
    expectedCheck: arraysMatch,
    category: 'Multi-JOIN',
  },
  {
    id: 100,
    title: 'Desafío Final: Dashboard Completo',
    description: 'Escribe una única consulta que muestre para cada cliente: nombre, país, número de pedidos, total gastado, ticket promedio por pedido y el producto más comprado. Solo incluye clientes con al menos 1 pedido.',
    difficulty: 'difícil',
    type: 'write',
    hint: 'Combina CTEs, JOINs, GROUP BY y subconsultas correlacionadas.',
    starterCode: '-- Desafío final: dashboard completo\nWITH ',
    validationQuery: `WITH stats AS (
  SELECT o.customer_id, COUNT(o.id) AS num_pedidos, SUM(o.total) AS total_gastado, AVG(o.total) AS ticket_prom
  FROM Orders o GROUP BY o.customer_id
),
top_producto AS (
  SELECT o.customer_id, p.title AS producto_top
  FROM Orders o
  INNER JOIN Products p ON o.product_id = p.id
  WHERE o.quantity = (SELECT MAX(o2.quantity) FROM Orders o2 WHERE o2.customer_id = o.customer_id)
  GROUP BY o.customer_id
)
SELECT c.name, c.country, s.num_pedidos, s.total_gastado, ROUND(s.ticket_prom, 2) AS ticket_prom, tp.producto_top
FROM Customers c
INNER JOIN stats s ON c.id = s.customer_id
LEFT JOIN top_producto tp ON c.id = tp.customer_id
ORDER BY s.total_gastado DESC`,
    expectedCheck: arraysMatch,
    category: 'Multi-JOIN',
  },
]
